#!/usr/bin/env bash
# configures a new Ubuntu machine to respect certain requirements
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
