#!/usr/bin/env bash
# redirection
apt-get -y update
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 1432-web-01 35.190.159.176:80 check
    server 1432-web-02 335.229.61.48:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
