#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
if [[ "$#" -eq 1 ]]; then
	mysqldump -uroot -p"$1" --all-databases > backup.sql
	tar -cvzf "$(date +"%d-%m-%Y")".tar.gz backup.sql
fi
