#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
NOW=$(date +"%d-%m-%Y")
mysqldump -uroot –p"$1" --all-databases > backup.sql
tar -cvzf "$NOW".tar.gz backup.sql
