#!/usr/bin/env bash
# script that:
# -Creates the file /var/run/holbertonscript.pid containing its PID
# -Displays To infinity and beyond indefinitely
# -Displays I hate the kill command when receiving a SIGTERM signal
# -Displays Y U no love me?! when receiving a SIGINT signal
# -Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
f=/var/run/holbertonscript.pid
trap "echo Y U no love me?!" INT
trap 'echo I hate the kill command;	rm "$f"; exit' TERM
trap 'rm "$f"; exit' QUIT
echo $$ > "$f"

while true
do
	echo To infinity and beyond
	sleep 2
done
