#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.
while IFS=':' read -r username pwd uid gid uidinf hdir cmdsh; 
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $hdir and rides $cmdsh."\
	"$uid's place is protected by the passcode $pwd,"\
	"more info about the user here: $uidinf"
done < /etc/passwd
