#!/usr/bin/env bash
# 7 lines or less                                                                           
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
